name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  move-to-todo:
    runs-on: ubuntu-latest
    if: github.repository == 'mcu-tools/mcuboot'
    steps:
      - uses: fojia/action-move-issues-to-column@master
        with:
          project: 'MCUboot releases'
          column: 'No Status'
          owner: 'mcu-tools'
          repo: 'action-move-issues-to-column'
          type: 'repo'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          marker: 'issue:todo'
