name: PR assignment

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.repository == 'mcu-tools/mcuboot'
    steps:
      - uses: actions/checkout@v1
      - uses: ohnogumi/auto-reviewers@v0.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: CODEOWNERS
